# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Detect(object):
    def setupUi(self, Detect):
        Detect.setObjectName("Detect")
        Detect.resize(520, 650)
        Detect.setWindowTitle("Detect")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Detect)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Detect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(520, 32))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.groupBox_3.setStyleSheet("background: #EBECEF;border: 1px solid #EBECEF;border-top-left-radius: 10px;border-top-right-radius: 10px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setContentsMargins(15, 8, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.closeButton = QtWidgets.QPushButton(self.groupBox_3)
        self.closeButton.setMinimumSize(QtCore.QSize(15, 15))
        self.closeButton.setMaximumSize(QtCore.QSize(15, 15))
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setToolTip("关闭")
        self.closeButton.setStyleSheet("#closeButton{border-image: url(:/icons/10.svg)}\n"
"#closeButton:hover{border-image: url(:/icons/11.svg)}")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_2.addWidget(self.closeButton, 0, 6, 1, 1)
        self.minButton = QtWidgets.QPushButton(self.groupBox_3)
        self.minButton.setMinimumSize(QtCore.QSize(15, 15))
        self.minButton.setMaximumSize(QtCore.QSize(15, 15))
        self.minButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minButton.setToolTip("最小化")
        self.minButton.setStyleSheet("#minButton{border-image: url(:/icons/18.svg)}#minButton:hover{border-image: url(:/icons/19.svg)}")
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.gridLayout_2.addWidget(self.minButton, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 17))
        self.label_2.setMaximumSize(QtCore.QSize(61, 17))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #1C1E25;")
        self.label_2.setText("坏帧检测")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.maxButton = QtWidgets.QPushButton(self.groupBox_3)
        self.maxButton.setMinimumSize(QtCore.QSize(15, 15))
        self.maxButton.setMaximumSize(QtCore.QSize(15, 15))
        self.maxButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maxButton.setToolTip("最大化")
        self.maxButton.setStyleSheet("#maxButton{border-image: url(:/icons/16.svg)}#maxButton:hover{border-image: url(:/icons/17.svg)}")
        self.maxButton.setText("")
        self.maxButton.setObjectName("maxButton")
        self.gridLayout_2.addWidget(self.maxButton, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setMinimumSize(QtCore.QSize(20, 20))
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setStyleSheet("image: url(:/icons/工具图标.png);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.skinButton = QtWidgets.QPushButton(self.groupBox_3)
        self.skinButton.setMinimumSize(QtCore.QSize(15, 15))
        self.skinButton.setMaximumSize(QtCore.QSize(15, 15))
        self.skinButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.skinButton.setStyleSheet("#skinButton{border-image: url(:/icons/14.svg)}\n"
"#skinButton:hover{border-image: url(:/icons/15.svg)}")
        self.skinButton.setText("")
        self.skinButton.setObjectName("skinButton")
        self.gridLayout_2.addWidget(self.skinButton, 0, 3, 1, 1)
        self.skinButton.raise_()
        self.minButton.raise_()
        self.maxButton.raise_()
        self.closeButton.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.stackedWidget = QtWidgets.QStackedWidget(Detect)
        self.stackedWidget.setMinimumSize(QtCore.QSize(520, 618))
        self.stackedWidget.setStyleSheet("background: #FFFFFF;border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;border: 0px solid #EBECEF;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolButton = QtWidgets.QToolButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(320, 382))
        self.toolButton.setMaximumSize(QtCore.QSize(640, 764))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.toolButton.setFont(font)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet("#toolButton{border: 1px solid #D4D4D4;border-radius: 4px;background-color: rgb(250, 250, 250);color: #8D9EA7;padding-top: 159px;padding-bottom:154px;}"
                                      "#toolButton:hover{color: #5481FF;background: #EDF2FF;border: 1px solid #5481FF;border-radius: 4px;padding-top: 159px;padding-bottom:154px;}")
        self.toolButton.setText("点击或拖拽文件上传检测")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(28, 28))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_3.addWidget(self.toolButton, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(320, 382))
        self.toolButton_2.setMaximumSize(QtCore.QSize(640, 764))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet("#toolButton_2{color: #5481FF;background: #EDF2FF;border: 1px solid #5481FF;border-radius: 4px;padding-top: 159px;padding-bottom:154px;}")
        self.toolButton_2.setText("点击或拖拽文件上传检测")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(28, 28))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_3.addWidget(self.toolButton_2, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(520, 40))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setStyleSheet("background: #FEE0CC;border: 0px solid;border-radius: 0px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setMinimumSize(QtCore.QSize(16, 16))
        self.label_18.setMaximumSize(QtCore.QSize(16, 16))
        self.label_18.setStyleSheet("image: url(:/icons/7.svg);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setText("文件路径中有中文名称，请检查重新上传")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 2, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 2, 0, 2, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_7.setContentsMargins(0, 175, 0, 292)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.label_19 = QtWidgets.QLabel(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(520, 20))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: #51596D;border: none;")
        self.label_19.setText("检测帧中，请稍等...")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.page_9)
        self.scrollArea.setMinimumSize(QtCore.QSize(514, 556))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("QScrollBar:vertical{width: 6px;border:0px solid;border-radius: 3px;margin: 0px,0px,0px,0px;background-color: transparent;background:#FFFFFF;}\n"
"\n"
"QScrollBar:vertical:hover{width: 6px;border:0px solid;margin: 0px,0px,0px,0px;background:#b5bcc5;}\n"
"\n"
"QScrollBar::handle:vertical{width:6px;background:#C6CED8;border-radius: 3px;}\n"
" \n"
"QScrollBar::handle:vertical:hover{background:#b5bcc5;}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 511, 556))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFFFFF;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(26, 0, 21, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 20, -1, 10)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(14, 12))
        self.label_13.setMaximumSize(QtCore.QSize(14, 12))
        self.label_13.setStyleSheet("image: url(:/icons/4.svg);border: none;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: #FA6400;border: none;")
        self.label_14.setText("坏帧")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_3.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-image: url(:/icons/5.svg);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_4.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("border-image: url(:/icons/6.svg);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(0, 14))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #999999;line-height: 14px;border: none;")
        self.label_9.setText("检测路径")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMinimumSize(QtCore.QSize(14, 12))
        self.label_10.setMaximumSize(QtCore.QSize(14, 12))
        self.label_10.setStyleSheet("image: url(:/icons/4.svg);border: none;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #FA6400;border: none;")
        self.label_11.setText("缺帧")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.pushButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_1.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_1.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setStyleSheet("border-image: url(:/icons/5.svg);")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_4.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_2.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(:/icons/6.svg);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 30, -1, 13)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #1C252A;line-height: 16px;border: 0px solid;border-radius: 0px;")
        self.label_8.setText("检测的        帧中，发现了        帧异常")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_9.setMinimumSize(QtCore.QSize(464, 0))
        self.groupBox_9.setStyleSheet("background: #FFF9F5;border-radius: 2px;color: #51596D;border: none;")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_8.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setMinimumSize(QtCore.QSize(464, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setText("")
        self.label_12.setWordWrap(True)
        self.label_12.setIndent(10)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.label_12.raise_()
        self.label_12.raise_()
        self.gridLayout_5.addWidget(self.groupBox_9, 4, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setMinimumSize(QtCore.QSize(464, 0))
        self.groupBox_10.setStyleSheet("background: #FFF9F5;border-radius: 2px;color: #51596D;border: none;")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_9.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setMinimumSize(QtCore.QSize(464, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background: #FFF9F5;border-radius: 2px;color: #51596D;border: none;")
        self.label_15.setWordWrap(True)
        self.label_15.setIndent(10)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.gridLayout_5.addWidget(self.groupBox_10, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(520, 60))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_6.setStyleSheet("background: #FFFFFF;border: 0px solid #EBECEF;border-top: 1px solid #EBECEF;border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 20px;background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(149, 187, 255, 255), stop:1 rgba(92, 134, 255, 255));color: #FFFFFF;")
        self.pushButton.setText("完成")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_20.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout.setContentsMargins(0, 150, 0, 225)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.label_7 = QtWidgets.QLabel(self.page_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(107, 113))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 113))
        self.label_7.setStyleSheet("image: url(:/icons/3.svg);border: none;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_16 = QtWidgets.QLabel(self.page_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(520, 20))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #51596D;border: none;")
        self.label_16.setText("检测的100帧中，暂未发现异常帧")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_5.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("border-radius: 20px;background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(149, 187, 255, 255), stop:1 rgba(92, 134, 255, 255));color: #FFFFFF;")
        self.pushButton_5.setText("完成")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_21.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.stackedWidget.addWidget(self.page_10)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.groupBox_3.raise_()
        self.toolButton.raise_()
        self.groupBox.raise_()
        self.groupBox_10.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.groupBox_10.raise_()
        self.label_17.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(Detect)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Detect)

    def retranslateUi(self, Detect):
        pass
import icons_rc
